server:
  port: 8000

spring:
  application:
    name: springboot-demo-app

  datasource:
    url: jdbc:mysql://mysql:3306/user_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
        initialization-fail-timeout: -1   # keep retrying until DB is ready
        connection-timeout: 30000         # optional: 30s timeout per attempt

        # Avoid startup errors if DB is not ready yet

  jpa:
    hibernate:
      ddl-auto: update   # Automatically create/update tables from entities
    show-sql: true       # Show SQL queries in console
    properties:
      hibernate:
       # Explicit dialect for Docker
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org.hibernate.SQL: debug                # Log SQL queries
    org.hibernate.orm.jdbc.bind: trace      # Log bound parameters
    org.springframework.web: info           # Optional: log web requests
